version: 2

project_name: jtk

before:
  hooks:
    - go mod tidy -C tools/jtk
    - go test ./tools/jtk/...

builds:
  - id: jtk
    dir: tools/jtk
    main: ./cmd/jtk
    binary: jtk
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/open-cli-collective/atlassian-go/version.Version={{.Version}}
      - -X github.com/open-cli-collective/atlassian-go/version.Commit={{.Commit}}
      - -X github.com/open-cli-collective/atlassian-go/version.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - tools/jtk/LICENSE
      - tools/jtk/README.md

# Linux packages (.deb and .rpm)
nfpms:
  - id: jtk
    package_name: jtk
    vendor: Open CLI Collective
    homepage: https://github.com/open-cli-collective/atlassian-cli
    maintainer: Open CLI Collective <https://github.com/open-cli-collective>
    description: Command-line interface for Jira Cloud
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: tools/jtk/LICENSE
        dst: /usr/share/licenses/jtk/LICENSE

# Homebrew cask with auto-quarantine removal for unsigned binaries
# Note: 'jira-ticket-cli' alias cask must be maintained manually in homebrew-tap
# (alternative_names requires GoReleaser Pro)
homebrew_casks:
  - name: jtk
    repository:
      owner: open-cli-collective
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/open-cli-collective/atlassian-cli
    description: "Command-line interface for Jira Cloud"
    binary: jtk
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
    caveats: |
      jtk has been installed.

      To configure, run:
        jtk config set --domain DOMAIN --email EMAIL --token TOKEN

      Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^Merge pull request'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other'
      order: 999

release:
  github:
    owner: open-cli-collective
    name: atlassian-cli
